### ISSUE TITLE
SAS Transport File V5 Support

### ISSUE THREAD

**Issue by jetravis** [WizardMac/ReadStat#84] opened 2016-10-04 22:52 UTC
Would it be possible to add SAS Transport File V5 as a supported file format? It is the required file format for submitting data to the FDA for regulatory review ([FDA StudyDataStandards](http://www.fda.gov/downloads/ForIndustry/DataStandards/StudyDataStandards/UCM384744.pdf) Section 3.3.1). [Here](http://support.sas.com/techsup/technote/ts140.pdf) is the technical specification for the format.

**Comment by hadley** [comment] 2016-10-05 11:47
Duplicate of #29

**Closed** 2016-10-26 05:34 UTC
