### ISSUE TITLE
Windows Build instructions incorrect

### ISSUE THREAD

**Issue by pds2208** [WizardMac/ReadStat#190] opened 2019-10-08 06:28 UTC
The Windows specific notes has 2 errors; one spelling mistake and make is needed to, eh, make

> pacman -S autoconf automake libtool mingw-w64-x86_64-toolchain ingw-w64-x86_64-cmake mingw-w64-x86_64-libiconv

should be

> pacman -S autoconf automake libtool mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake mingw-w64-x86_64-libiconv make

**Comment by evanmiller** [comment] 2019-10-08 09:55
Duplicate of #189

**Closed by evanmiller** 2019-10-08 09:55 UTC

**Comment by pds2208** [comment] 2019-10-08 09:58
Thanks but the make command still needs to be installed on windows as above.

**Comment by evanmiller** [comment] 2019-10-08 10:24
Thanks, will fix
