### ISSUE TITLE
The following sas7bdat from census failed to be parsed

### ISSUE THREAD

**Issue by huapeng01016** [WizardMac/ReadStat#162] opened 2018-12-23 18:26 UTC
We get a parse error using the latest ReadStat to convert the following sas7bdat file. 

[AHS 2013 National Public Use File PUF Flat File](http://www2.census.gov/programs-surveys/ahs/2013/AHS%202013%20National%20PUF%20v1.2%20Flat%20SAS.zip?#)

**Comment by evanmiller** [comment] 2018-12-23 19:21
Duplicate of #21

**Closed by evanmiller** 2018-12-23 19:21 UTC

**Comment by ofajardo** [comment] 2018-12-24 07:47
That error code would indeed be very helpful.

**Comment by evanmiller** [comment] 2018-12-24 12:43
The error code I receive with this file is `READSTAT_ERROR_UNSUPPORTED_COMPRESSION`. Do you see something different?

**Comment by evanmiller** [comment] 2020-08-26 01:28
Please try the new code branch:

https://github.com/WizardMac/ReadStat/tree/sas-binary-compression
