### ISSUE TITLE
Readstat does not support compression type SASYZCR2

### ISSUE THREAD

**Issue by mirhyman** [WizardMac/ReadStat#205] opened 2020-05-22 16:33 UTC
This might be a duplicate of an issue already open here (https://github.com/WizardMac/ReadStat/issues/21) but I don't know if this is technically binary compression or not so opening a new one just in case..feel free to close it if it is in fact a duplicate.

I have a file which is a file with dummy data created using this compression scheme. 
I found the sas7bdat python library and used it to print out the information for this file to get a better sense of what compression scheme is not supported.

When I try to read this file I get a "compression scheme not supported" error.

[totalcallsmade.sas7bdat] Header:
	col_count_p1: 10
	col_count_p2: 0
	column_count: 10
	compression: SASYZCR2
	creator: None
	creator_proc: None
	date_created: 2020-04-11 16:09:32.996401
	date_modified: 2020-04-11 16:09:32.996401
	endianess: big
	file_type: DATA
	filename: totalcallsmade.sas7bdat
	header_length: 65536
	lcp: 8
	lcs: 0
	mix_page_row_count: 809
	name: TOTALCALLSMADE
	os_name: 00FAEEDB
	os_type: 7.2
	page_count: 0
	page_length: 65536
	platform: unix
	row_count: 411
	row_length: 77
	sas_release: 9.0401M6
	server_type: AIX
	u64: True

Contents of dataset "TOTALCALLSMADE":
Num Name                   Type   Length Format Label              
--- ---------------------- ------ ------ ------ -------------------
  1 month                  number      8                           
  2 year                   number      8                           
  3 lobFilter              string      3                           
  4 ELIGIBLE_MEASURE       string     10 $      ELIGIBLE_MEASURE   
  5 successfully_called    number      8                           
  6 unsucessfull_call      number      8                           
  7 lvm_call               number      8                           
  8 autoclose_call         number      8                           
  9 total_calls            number      8                           
 10 success_rate           number      8        

[totalcallsmade.zip](https://github.com/WizardMac/ReadStat/files/4669275/totalcallsmade.zip)

**Comment by evanmiller** [comment] 2020-08-26 00:24
Please try the `sas-binary-compression` branch here:

https://github.com/WizardMac/ReadStat/tree/sas-binary-compression

**Comment by evanmiller** [comment] 2020-08-27 18:17
The provided file opens OK with that branch, so I am closing this issue as a duplicate of #201 

If you still have issues with the `dev` branch, please open a new issue. (The change will make its way to `master` later.)

**Closed by evanmiller** 2020-08-27 18:17 UTC
