### ISSUE TITLE
Fail to parse sas7bcat file

### ISSUE THREAD

**Issue by jmurray1022** [WizardMac/ReadStat#38] opened 2015-10-09 13:51 UTC
On loading the SAS files for the 2014 NYTS I get an error about the associated cat file:

"Error: Failed to parse /Users/jared/Dropbox/nyts/nyts2014_formats.sas7bcat: Invalid file, or file has unsupported features."

The data itself appears to load fine, and I have every reason to think the cat file is valid and works in SAS. The files are available at:

http://www.cdc.gov/tobacco/data_statistics/surveys/nyts/

**Comment by evanmiller** [comment] 2015-10-09 14:20
I am able to reproduce the problem. I'll post back when I have more information about it.

**Comment by evanmiller** [comment] 2015-10-09 15:09
This commit should fix the issue: https://github.com/WizardMac/ReadStat/commit/663554ef6eb3909d2bd0bfe23735075124365227

You can update your copy of ReadStat with the instructions here:

https://github.com/hadley/haven#updating-readstat

**Comment by jmurray1022** [comment] 2015-10-11 15:19
Thanks! Had a chance to try it out and its early there - everything loads fine, but the labels are off by 1 (they start from 0 but should start from 1).

**Comment by evanmiller** [comment] 2015-10-12 05:08
Thanks for the update. I'll look into the 0/1 issue.

**Comment by evanmiller** [comment] 2015-10-12 05:47
Think I've found the underlying issue for the off by 1 problem -- this commit should fix it: https://github.com/WizardMac/ReadStat/commit/450f43068a1b35ae10d69be14240d6ab5b29ffa4

Please try out the latest code and let me know if it works as expected now.

**Comment by evanmiller** [comment] 2015-10-12 15:08
Since the parse error is fixed I'm going to close this issue. Let's continue the discussion about the off-by-1 problem over here: https://github.com/WizardMac/ReadStat/issues/40

**Closed by evanmiller** 2015-10-12 15:08 UTC
