### ISSUE TITLE
Error on fresh install (debian stretch)

### ISSUE THREAD

**Issue by tafia** [WizardMac/ReadStat#101] opened 2017-11-24 04:48 UTC
```
$ make
  CC       src/libreadstat_la-CKHashTable.lo
  CC       src/libreadstat_la-readstat_bits.lo
  CC       src/libreadstat_la-readstat_convert.lo
  CC       src/libreadstat_la-readstat_error.lo
  CC       src/libreadstat_la-readstat_io_unistd.lo
  CC       src/libreadstat_la-readstat_parser.lo
  CC       src/libreadstat_la-readstat_value.lo
  CC       src/libreadstat_la-readstat_variable.lo
  CC       src/libreadstat_la-readstat_writer.lo
  CC       src/sas/libreadstat_la-ieee.lo
  CC       src/sas/libreadstat_la-readstat_sas.lo
  CC       src/sas/libreadstat_la-readstat_sas7bcat_read.lo
  CC       src/sas/libreadstat_la-readstat_sas7bcat_write.lo
  CC       src/sas/libreadstat_la-readstat_sas7bdat_read.lo
src/sas/readstat_sas7bdat_read.c: In function ‘sas7bdat_init_variable’:
src/sas/readstat_sas7bdat_read.c:517:101: error: ‘%s’ directive output may be truncated writing up to 1023 bytes into a region of size between 435 and 954 [-Werror=format-truncation=]
                         "ReadStat: Error converting variable #%d info to specified encoding: %s %s (%s)\n",
                                                                                                     ^~
src/sas/readstat_sas7bdat_read.c:516:17: note: ‘snprintf’ output between 73 and 1615 bytes into a destination of size 1024
                 snprintf(error_buf, sizeof(error_buf),
                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                         "ReadStat: Error converting variable #%d info to specified encoding: %s %s (%s)\n",
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                         i, variable->name, variable->format, variable->label);
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
Makefile:1432: recipe for target 'src/sas/libreadstat_la-readstat_sas7bdat_read.lo' failed
make: *** [src/sas/libreadstat_la-readstat_sas7bdat_read.lo] Error 1
```

**Comment by evanmiller** [comment] 2017-11-24 22:28
Duplicate of #100

**Closed by evanmiller** 2017-11-24 22:28 UTC
