### ISSUE TITLE
problem with CHAR compressed SAS datasets

### ISSUE THREAD

**Issue by reikoch** [WizardMac/ReadStat#42] opened 2015-11-06 10:19 UTC
moved from [https://github.com/hadley/haven/issues/131].

Not all char compressed SAS datasets can be read; possibly when a certain size is exceeded.

An example dataset with 16 MB random generated data you find as "bar.sas7bdat" in [https://github.com/reikoch/testfiles].

read_sas refuses to read it with the message

> read_sas('~/xx/bar.sas7bdat')
> Error: Failed to parse /opt/BIOSTAT/home/kochr4/xx/bar.sas7bdat: Invalid file, or file has unsupported features.

Subsets of this file bar.sas7bdat, like barrows (first 1000 rows of bar) and barcols (last 15 columns dropped), work fine.

**Comment by evanmiller** [comment] 2015-11-24 08:18
Notes for myself:

It appears that a subheader pointer in `bar.sas7bdat` is pointing to compressed data, but the pointer itself indicates that the data is not compressed. (The byte at offset 5809096 is `0x00`, whereas all of the other pointers in the block have the value `0x04`.) In a way the issue is the converse of #37. I'm not sure if the compression bit is stored elsewhere or if a workaround is required here.

**Comment by reikoch** [comment] 2015-11-24 08:41
If it helps I can produce a really char compressed dataset, not just one labelled so. I see problems with char compressed datasets so often that I do not believe it to be restricted to "wrong" labelling.

**Comment by evanmiller** [comment] 2015-11-24 08:44
The data you provided is indeed compressed. The "mislabeling" occurs for a short segment of data deep in the file. The trouble occurs because a compressed file can contain both compressed and uncompressed chunks, and these individual chunks are sometimes mislabeled (apparently).

**Comment by reikoch** [comment] 2015-12-10 13:50
Most char compressed SAS datasets can now be read by development version 0.2.0.9000 of haven. But the simple example ietest2.sas7bdat in [https://github.com/reikoch/testfiles/blob/master/ietest2.sas7bdat] returns for read_sas("ietest2.sas7bdat"):
> ReadStat: Error parsing page 0, bytes 8192-16383

> Error: Failed to parse /opt/BIOSTAT/home/kochr4/sas7bdat/ietest2.sas7bdat: Invalid file, or file has unsupported features.

**Comment by reikoch** [comment] 2015-12-15 11:10
It looks like Python module __sas7bdat__ from [https://bitbucket.org/jaredhobbs/sas7bdat] has solved  decoding of SAS compressed datasets...

**Comment by evanmiller** [comment] 2016-06-03 14:44
Fixed in https://github.com/WizardMac/ReadStat/commit/c92f6976288a88ae8abfeee9e8aa4f5b7a187b9a

Please re-open the issue if you are still experiencing problems.

**Closed by evanmiller** 2016-06-03 14:44 UTC

**Comment by reikoch** [comment] 2016-06-03 15:10
Excellent - it works for my test files!
Thanks lots!
